### ISSUE TITLE
AF_PACKET desired

### ISSUE THREAD

**Issue by gdamore** [zerotier/libzt#13]
I have a use case where I want to use the layer 2 stuff directly, without needing the L3/4 stuff (i.e. no IP, TCP, etc.)

I can build this using libzerotiercore, but it seems like it would be nicer if the SDK offered an AF_PACKET style support.

I do not believe it is necessary to support all the Linux options there (e.g. no need for rings in first version, or fanout, or some of the other socket options -- I think only the socket options for managing multicast are really necessary for full functionality, and initially even those could be elided (I don't need them for example).  

The details of the AF_PACKET family on Linux are here:

http://man7.org/linux/man-pages/man7/packet.7.html

I think this is an excellent starting point for offering L2 style capabilities to userland.

**Comment by gdamore** [comment]
Note: I may be able to work on implementing this, provided @janjaapbos and the ZT team agree.

**Comment by gdamore** [comment]
Btw, AF_RAW is probably also useful for direct IP access in some circumstances; I don't need it though.

**Comment by gdamore** [comment]
(I guess that's SOCK_RAW rather.)

**Comment by joseph-henry** [comment]
Sounds like a plan. So, `src/libzt.cpp` contains our implementations of various socket api calls. We will want to section off a portion of that with something like a `NO_STACK=1` sort of build option. 

Points of interest:

1). RX,`SocketTap::put` receives raw frames and dumps them into the userspace stack.
2). TX, `SocketTap::_handler` will send raw frames from the userspace stack into the ZT core. 

I'm actually working on a new stack driver with a BSD license and as a result will be making it a bit easier to omit the stack driver code, I'll try to push this tonight.

**Comment by joseph-henry** [comment]
Ok, now try something like, `make static_lib NO_STACK=1 LIBZT_IPV4=1; make tests` 

Check out `test/layer2.cpp` which is a minimal example which I'd like to flesh out and can serve as a starting point.

Once built, try: `./build/$(PLATFORM)/layer2 [zt_home_dir] [nwid]`. It'll start a ZT core instance, and spit out an identity once added to a network, attempt to create an unimplemented SOCK_RAW and exit.

**Comment by gdamore** [comment]
Cool, I'll have a look at this.

**Comment by joseph-henry** [comment]
I've got basic VL2 support working with the `layer2.cpp` example mentioned above, I'll be pushing it today, that should serve as a good starting point. It builds the socket, uses basic `ioctl()` calls to get the virtual interface/address info and sends a packet via `sendto()`. After this I'm going to shift my efforts back to fleshing out the `lwIP` driver code.

However, I have a question which I think comes down to preference but I'm thinking about supplying a single linux-like raw socket API even on non-linux platforms. It seems easiest to provide one API instead of trying to make a native feel for each platform. 

For instance, you might use `ioctl()` calls to get information about the ZT virtual interface in the same way we would about a regular interface on linux, but macOS doesn't have that same analog for every case, so if built on a non-linux platform I'll just define the necessary stuff to make it work like it would on linux. 

Thoughts?
