### ISSUE TITLE
iOS Support (raw packets)

### ISSUE THREAD

**Issue by JiaoLiu** [zerotier/libzt#132]
Hello, how can i use this lib with apple network extension?  Is there any example?
I started a packet tunnel to block requests, but the latest lib doesn't contain api to inject packets.

**Comment by joseph-henry** [comment]
Correct, the library as is does not allow you to inject raw packets but it is not impossible. The raw Ethernet frames are currently sent from the user-space network stack to ZeroTier [here](https://github.com/zerotier/libzt/blob/20e20be0f3436bc2a859b79efae884a68293d452/src/VirtualTap.cpp#L373). (see: `zts_lwip_eth_rx` and `zts_lwip_eth_tx`)

`zts_lwip_eth_rx` is called by ZeroTier when a packet is to be given to the network stack.

`tap->_handler(tap->_arg, NULL, tap->_net_id, src_mac, dest_mac, proto, 0, data, len)` is called from the network stack in order to feed a packet into ZeroTier.

While we don't have an API call for this yet it could be added. If you make a PR I would gladly consider merging it

**Comment by JiaoLiu** [comment]
😂，Thx。
I finally achieve the "packettunnel" function with the lower-level c++ api & oc wrapper(like [ZeroTier-iOS](https://github.com/weibo3721/ZeroTier-iOS) do).
I'm not  very familiar with c programming, and I have some UI level programming work to do。I will make a PR when I'm free.

**Comment by joseph-henry** [comment]
Very good! Let me know if you need any help. I'll close this ticket for now.

**Comment by woodey233** [comment]
Is this feature supported now?
