### ISSUE TITLE
Need Windows support?

### ISSUE THREAD

**Issue by gdamore** [zerotier/libzt#14]
I notice that the top-level Makefile does not seem to deal with Windows.   Would be nice to fix this.

**Comment by joseph-henry** [comment]
I have some experimental code that works on Windows (mainly just a bunch of small tweaks), I'll create a branch for this here shortly and start introducing the changes probably next week.

**Comment by gdamore** [comment]
Cool.

**Comment by joseph-henry** [comment]
Windows support has been added in `1.1.5` as of commit 4f6908b and appears to be pretty stable.

Since building on Windows is a little trickier I'll soon be placing pre-built DLLs and static libraries on our main site's download page. But if anyone wants to built it on their own they can follow these steps:

 - Set up [mingw-w64](https://mingw-w64.org/doku.php)
 - Install a copy of [MSYS](http://www.mingw.org/wiki/MSYS)
 - Run `msys.bat` (should be in the base directory of your MSYS installation)
 	- Tell it where your `mingw-64` installation is
 - `make static_lib`
 - `make tests`

 This will output binaries to `build/mingw-w64`

I do have plans to simplify this process but I'll save that effort for another time.

**Comment by wmdfy** [comment]
> Windows support has been added in `1.1.5` as of commit [4f6908b](https://github.com/zerotier/libzt/commit/4f6908bb7cdc8c0a04f52cca1766cb16050c81d6) and appears to be pretty stable.
> 
> Since building on Windows is a little trickier I'll soon be placing pre-built DLLs and static libraries on our main site's download page. But if anyone wants to built it on their own they can follow these steps:
> 
> * Set up [mingw-w64](https://mingw-w64.org/doku.php)
> * Install a copy of [MSYS](http://www.mingw.org/wiki/MSYS)
> * Run `msys.bat` (should be in the base directory of your MSYS installation)
>   
>   * Tell it where your `mingw-64` installation is
> * `make static_lib`
> * `make tests`
> 
> This will output binaries to `build/mingw-w64`
> 
> I do have plans to simplify this process but I'll save that effort for another time.

Now have a DLL can download?
