### ISSUE TITLE
http traffic

### ISSUE THREAD

**Issue by asbjornenge** [zerotier/libzt#2]
Hi again!

I tried running an http service in a Network Container (docker). I can ping the container and connect to the port (telnet), but I can't seem to get any http traffic through. Just hangs :confused: 

Any idea why this might be?

Regards,
Asbjørn

**Comment by joseph-henry** [comment]
Try commenting out `#include <sys/socket.h>` in `src/SDK_Intercept.c` and rebuild the intercept with `make linux_intercept`, this prevents the proper interception of the socket api symbols and might be responsible. I'll perform a test myself to see what the issue is. 

Additionally, when you build you can use the `SDK_DEBUG=1` flag to turn on debugging. However I have improved debugging facilities coming in the next update later today.

I'll update you on what I find out.

**Comment by asbjornenge** [comment]
Commenting out `#include <sys/socket.h>` it complains about `Invalid argument` and `Operation not supported` for `setsockopt()` (see below). However, the http request got through! :tada: But, as you can see from the latter, it never returns :confused: 

```
setsockopt():
: Invalid argument
setsockopt():
: Operation not supported
Listening on port 3000
GOT A GET
```

```
❯ curl -v -XGET 10.247.10.69:3000
* Rebuilt URL to: 10.247.10.69:3000/
* Hostname was NOT found in DNS cache
*   Trying 10.247.10.69...
* Connected to 10.247.10.69 (10.247.10.69) port 3000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 10.247.10.69:3000
> Accept: */*
> 
```

**Comment by asbjornenge** [comment]
Any updates on this @joseph-henry ?

**Comment by joseph-henry** [comment]
Hey, sorry I haven't gotten back to you yet! I'm actually upgrading the stack we're using and doing some core upgrades that I'll push to the dev branch this Friday if all goes well. This issue is still on my list but I haven't quite gotten to it yet. Could you tell me more about the http service you're running? What is it exactly?

I ask because I'm curious what the options it's setting in `setsockopt()`. I'll have improved debug outputs so we can determine what it's doing.

**Comment by asbjornenge** [comment]
Trying to get back to you with some relevant code, I decided to push my 3 part container setup to GitHub. I made a [ubuntu-zero](https://github.com/asbjornenge/ubuntu-zero) container, which is the basis for [node-zero](https://github.com/asbjornenge/node-zero) which is the basis for [app-node-zero](https://github.com/asbjornenge/app-node-zero) :stuck_out_tongue_closed_eyes: 

The funny part is; now it works just fine :stuck_out_tongue_winking_eye: :see_no_evil:

Using my initial build I don't get any `setsockopt()` issues, and I can both `GET` and `POST` to the container/app. So yeah... I don't know what the issue was before, but it might have been something with the app or the network or something (I was on a different network last time I worked on this).

I was planning to write this up in a blogpost. Do you think this is a bit premature to start blogging about the SDK and using it like this, or...?

In any case I'll keep working on this and testing with large `body` data, other more complex applications etc. I'll be sure to report back if I have any problems. Feel free to close the issue if you see fit :smile: :+1:

**Comment by asbjornenge** [comment]
Alright, seems I wasn't quite finished with this issue after all :stuck_out_tongue_closed_eyes: Seems it hangs (unable to find the route back?) if I include a `payload` **AND** read it :anguished: 

I made the following simple `express` APIs.

```
app.post('/json', jsonParser, function(req, res) {
  console.log('GOT THE POST', req.body)
  res.send('welcome, ' + req.body.username)
})

app.post('/form', urlencodedParser, function(req, res) {
  console.log('GOT THE POST', req.body)
  res.send('welcome, ' + req.body.username)
})
```

Where the `jsonParser` and `urlencodeParser` parses `Content-Type: application/json` and `Content-Type: application/x-www-form-urlencoded` respectively.

Consider the following `cURLs`

```
curl -XPOST localhost:3000/json --data '{ "username": "pony" }' -H "Content-Type: application/json"
curl -XPOST localhost:3000/form --data "username=pony" -H "Content-Type: application/x-www-form-urlencoded"
```

In the case of running the app on `localhost` they both respond with `welcome, pony` as would be expected. However, running them in my [node-zero](https://github.com/asbjornenge/node-zero) container, they never return.

```
curl -v -XPOST 10.247.13.39:3000/form --data "username=pony" -H "Content-Type: application/x-www-form-urlencoded"
* Hostname was NOT found in DNS cache
*   Trying 10.247.13.39...
* Connected to 10.247.13.39 (10.247.13.39) port 3000 (#0)
> POST /form HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 10.247.13.39:3000
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 13
> 
* upload completely sent off: 13 out of 13 bytes
<<<HANGS HERE>>>
```

Leaving out the `--.data` parameter, or even changing the `Content-Type` header (resulting in the parser being skipped and the payload not read) causes the request to return as normal, but with the response of `welcome, undefined` - which is also to be expected in this case.

They are however, both of them (localhost and zerotier), able to read and parse the payload. The server in either case report:

```
GOT THE POST { username: 'pony' }
```

So it seems to be related to ***returning*** **after reading the request payload** for some weird reason!?

Any and all help/tips/ideas are very welcome :smile: :+1:

**Comment by joseph-henry** [comment]
Additionally, you can get the addresses of the sdk service instance on your networks via `./zerotier-cli -D$SDK_PATH listnetworks` once it's started. You'll want to perform your requests to those addresses.

**Comment by asbjornenge** [comment]
Hmm... If you take a look at my [ubuntu-zero init script](https://github.com/asbjornenge/ubuntu-zero/blob/master/init-zerotier.sh), it's the one being called at the top of the [app-node-zero init script](https://github.com/asbjornenge/app-node-zero/blob/master/start.sh) (`init-zerotier`) and is doing most of the lifting. It's pretty close to [docker_demo/sdk_entrypoint.sh](https://github.com/zerotier/ZeroTierSDK/blob/master/integrations/docker/docker_demo/sdk_entrypoint.sh).

I am using `zerotier-sdk-service` in the same way as the `docker_demo/sdk_entrypoint.sh`. One difference between these two and your example above is the port number - `9993` (standard zerotier) vs. `9994` - is this a typo above?

If I try to use your example above I get:
```
zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-sdk
```

**Comment by asbjornenge** [comment]
Initially, in my [start.sh](https://github.com/asbjornenge/app-node-zero/blob/master/start.sh) script, I call the `init-zerotier` cmd. Which is [this](https://github.com/asbjornenge/ubuntu-zero/blob/master/init-zerotier.sh) script. Basically a copy of [docker_demo/sdk_entrypoint.sh](https://github.com/zerotier/ZeroTierSDK/blob/master/integrations/docker/docker_demo/sdk_entrypoint.sh). It is running `zerotier-sdk-service` as a daemon etc.

Using your script above, I get it working, but I have the same issue as before :confused: 

Also, in your script above, you are using port `9994`, is that a typo? I'm using port `9993`.

**Comment by asbjornenge** [comment]
@joseph-henry hi! Has work on the `SDK` halted? Still would :heart: to get this working properly.

**Comment by asbjornenge** [comment]
FYI: Building with `clang` installed make a big difference :tada: :stuck_out_tongue: Fallback `gcc / g++` fails on my fairly standard ubunut box at least.

**Comment by joseph-henry** [comment]
Hey Asbjorn, sorry I've been incommunicado lately, I've been knee deep in a refactor of a large portion of the SDK. We now have support for multiple network stacks (picoTCP was added), and now IPV6. The API hasn't changed hardly at all. Once I finish a little more testing I might push it to the dev branch.

**Comment by asbjornenge** [comment]
@joseph-henry thanks for the update :smile: I'll keep a lookout for pushes to the `dev` branch :tada:

**Comment by joseph-henry** [comment]
@asbjornenge I've pushed the latest internal dev to our public github, you should be able to pull it from dev now. I haven't completed all of the unit tests for this build but I've verified that you can connect/accept connections in both IPv4 and IPv6 as well as with both `lwIP` and `picoTCP`.

Some notes:

Since we now provide multiple stack support you'll need to specify the stack and protocol version you wish to use. For example: `make linux_service_and_intercept SDK_LWIP=1 SDK_IPV4=1` or `make linux_service_and_intercept SDK_PICOTCP=1 SDK_IPV6=1`, etc

Also, if you use `picoTCP`, make sure you copy `libpicotcp.so` instead of `liblwip.so`.

I haven't put it through a round of heavy stress testing yet but I will early next week. If you get hung up on something shoot me an email directly before you spend all day on the issue (I believe you already have my email). I'll be out of town this weekend and will respond quicker via email. We've also sent you an invite to join our public-sdk Slack channel.

Good luck!
