### ISSUE TITLE
Build/install improvements wishlist

### ISSUE THREAD

**Issue by fnoop** [zerotier/libzt#22]
- [Would be nice to build the static library into lib/ which is where it would be expected in use]
 - [Shared library would be nice]: oh already has one, but broken, will raise separate issue 
 - [Make all target would be nice]
 - [Make install target would be nice]

Thanks for the library :)

**Comment by joseph-henry** [comment]
Noted, I'll look into improving this. 

Also which shared library build are you having issues with? There's a few variants based on flags you might use.

**Comment by joseph-henry** [comment]
I've posted the same text in another issue, but will post it again here since other people might search and find this.

We've since transitioned to a CMake-based build system.

To build all targets (including shared libraries) use:

```
git submodule init
git submodule update
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=DEBUG
cmake --build build 
```

The output will be located in `bin/lib`. Ignore all products except `libzt.so`, `libzt.dylib`, and `libzt.a`.

No install script yet, but I'll look into it.
