### ISSUE TITLE
IPv6 TCP connection fails to connect shortly after client and server join the ZeroTier network

### ISSUE THREAD

**Issue by pts** [zerotier/libzt#38]
I'm experiencing IPv6 TCP connection timeouts when connecting shortly after client and server have joined the ZeroTier network Earth. By expectation is that TCP connections succeed right after `zerotier-one -q listnetwork` has indicated that the join was OK.

For the record, here are the terminal window dumps.

On the client:

```
$ telnet PUBLIC_IP_ADDRESS_OF_SERVER  # Gets the SSH-2.0- in <0.3 seconds.
Trying PUBLIC_IP_ADDRESS_OF_SERVER...
Connected to PUBLIC_IP_ADDRESS_OF_SERVER.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3
^C
Connection closed by foreign host.
```

On the server:
  
```
$ telnet 127.0.0.1 22
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3
^C
Connection closed by foreign host.
$ zerotier-one -q join 8056c2e21c000001
200 join OK
$ while ! zerotier-one -q listnetworks |
  grep -q ' earth[.]zerotier[.]net .* OK PUBLIC '; do echo .; sleep 1; done
.
.
.  
.  
$ zerotier-one -q listnetworks | grep ' earth[.]zerotier[.]net .* OK PUBLIC '
200 listnetworks 8056c2e21c000001 earth.zerotier.net ??:??:??:??:??:?? OK PUBLIC ztmjfmfyq5 fd80:????:????:????:????:????:????:????/88,28.???.???.???/7
```

On the client:
  
```
$ zerotier-one -q join 8056c2e21c000001
200 join OK
$ while ! zerotier-one -q listnetworks |
  grep -q ' earth[.]zerotier[.]net .* OK PUBLIC '; do echo .; sleep 1; done
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
$ telnet fd80:????:????:????:????:????:????:???? 22  # Takes about 10 seconds to time out.
Trying fd80:????:????:????:????:????:????:????...
telnet: Unable to connect to remote host: Connection timed out
$ telnet fd80:????:????:????:????:????:????:???? 22
Trying fd80:????:????:????:????:????:????:????...
Connected to fd80:????:????:????:????:????:????:????.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3
```

The bug is indicated by the `telnet: Unable to connect to remote host: Connection timed out` line. By this time this connection should succeed, because both the client and the server have joined the ZeroTier network Earth with status `OK PUBLIC`.

This is also happening if the client is using libzt to connect to the ZeroTier network Earth, and the server has been connected for >10 minutes (see the details in https://github.com/zerotier/libzt/issues/31#issuecomment-429885564):

```
$ ./a.out
error connecting to remote host: -1 Software caused connection abort
```

**Comment by pts** [comment]
> Does this mean that you can only reproduce this if the server has been connected for more than 10 minutes (or) that despite being connected for over 10 minutes this still happens?

It means the latter: despite being connected for over 10 minutes this still happens? I haven't tried connecting with libzt immediately after the server joins, but I've tried connecting immediately without libzt, see that in https://github.com/zerotier/libzt/issues/31 .

**Comment by joseph-henry** [comment]
This ticket has been open for quite a while but I believe these issues are fixed in the most recent version.

I believe the issue you were experiencing is related to our underlying transport-triggered link provisioning which creates unexpected behavior in a normal `zts_connect()` call. I've added a lengthy but worthwhile blurb about this with a suggested mitigation to the example sources in the `examples/cpp` folder.

In this latest version there are a couple of changes to be aware of:
 - Main C API header has been renamed to `ZeroTierSockets.h`
 - Error reporting scheme and values have changed slightly (see header file)
 - Event code values have changed significantly (see header file)
 - Download link: https://download.zerotier.com/dist/sdk
 - Updated [README.md](https://github.com/zerotier/libzt/blob/master/README.md)

Let me know if this issue persists or you discover anything else.
