### ISSUE TITLE
Prebuilt Windows binaries are linked with Debug configuration

### ISSUE THREAD

**Issue by evshiron** [zerotier/libzt#40]
I downloaded [libzt.dll](https://download.zerotier.com/RELEASES/1.2.12/dist/libzt/win/libzt-1.2.0r1-win10-x86-release.dll) and used FFI to load the library, but received the following logs:

```
0009:err:module:import_dll Library MSVCP140D.dll (which is needed by L"\\libzt-1.2.0r1-win10-x86-release.dll") not found
0009:err:module:import_dll Library VCRUNTIME140D.dll (which is needed by L"\\libzt-1.2.0r1-win10-x86-release.dll") not found
0009:err:module:import_dll Library ucrtbased.dll (which is needed by L"\\libzt-1.2.0r1-win10-x86-release.dll") not found
panic: Module not found.
```

After switching to `MinSizeRel` in Visual Studio and build, the result is around 700KB and is successfully loaded.

EDIT: fix the link, x86 version was used.

**Comment by joseph-henry** [comment]
Thanks for opening this. This ticket has been open for quite a while but I believe this issue is fixed in the most recent version. Additionally, I've updated the download link: https://download.zerotier.com/dist/sdk which includes Windows static and dynamic libraries.
In this latest version there are a couple of changes to be aware of:
 - Main C API header has been renamed to `ZeroTierSockets.h`
 - Error reporting scheme and values have changed slightly (see header file)
 - Event code values have changed significantly (see header file)
 - Updated [README.md](https://github.com/zerotier/libzt/blob/master/README.md)

Let me know if this issue persists or you discover anything else.
