### ISSUE TITLE
How to set routes at runtime?

### ISSUE THREAD

**Issue by evshiron** [zerotier/libzt#42]
I am building a mesh network using `libzt` and wanna give nodes the ability to choose a moon as the gateway to access other networks. I have considered SNAT and DNAT on moons but the application will be unable to know its peers so I want to stick with the route way.

I discover that `ZT1Service.hpp` has a `zts_get_network_routes` function, and the source code does have functions to synchronize managed routes, but I don't know how it will take effects and whether they will work if I modify the routes later.

Would you mind giving me some instructions about it? Thanks in advance.

**Comment by joseph-henry** [comment]
This is an old but still relevant ticket. The API currently lets you `orbit a moon` but that terminology will likely change in the series `2.X` ZeroTier. The API doesn't allow one to manually set routes locally. This is normally done via our web API.

Just a side note: libzt will obey traditional configuration options in a `local.conf`.

Since this ticket is so old I'd like to ask if this is still an issue or if you've found a workaround in your design.
