### ISSUE TITLE
C# Examples/Interop Gone?

### ISSUE THREAD

**Issue by nixcamic** [zerotier/libzt#49]
I went to build a C# project using the previous C# code that was up here and noticed it's all been removed, was that by accident, or was it removed for a reason? Will the previous code still work with the current library?

**Comment by bbatchelder** [comment]
I was doing some work on enhancing the C# interop about 8 months ago, and am just now coming back to the project.  You can give my project a try until we find out why they deleted the C# interop examples that were a part of this project.

https://github.com/bbatchelder/libzt-interop

**Comment by joseph-henry** [comment]
Hey everyone. There's some new interop work ([examples/csharp](https://github.com/zerotier/libzt/tree/master/examples/csharp)) which hopefully should be a bit more idiomatic than our previous efforts. Additionally I've included a new PowerShell script (8ab6ee07c022f63496cd5d71c73ab57873ac4a45 ) to make handling the CMake build process a little easier. See the main README for updated build instructions for each platform, you may need to slightly modify the `examples/csharp/Makefile` for your particular setup.

This code is a work in progress but does work and should reach maturity in the next week or so. Please let me know or make a PR if anything seems funky or you have a better idea of how something should be done.

And btw, thank you @bbatchelder for your early work on this.

**Comment by MoogleTroupe** [comment]
I'm getting a crash with the latest version of this, both with the example and my own test- the delegate is garbage collected. In your example call GC.Collect() after a join, it will crash.

**Comment by MoogleTroupe** [comment]
I fixed the issue I was having.  https://github.com/zerotier/libzt/pull/99

**Comment by MoogleTroupe** [comment]
@joseph-henry no rush, but I was wondering if ipv6 support as well as an api call to get the ipv6 address of the node will be added eventually?  I'm playing around with a private network on ipv4 and it works well, but for my use case ad-hoc ipv6 would be fine.

**Comment by joseph-henry** [comment]
@MoogleTroupe Check out the latest package `1.4.1`, and [test/selftest.cs](https://github.com/zerotier/libzt/blob/master/test/selftest.cs)

An IPv6 capable socket can now be created by swapping `AddressFamily.InterNetwork` for `AddressFamily.InterNetworkV6`. And there's a small block in there showing how to get assigned addresses and routes.

As of right now there is a limit to `one` assigned address per family (v4 or v6) per network. This is due to libzt's virtual ethernet driver implementation but I will be fixing that in the future.
