### ISSUE TITLE
fail when building libzt at windows os

### ISSUE THREAD

**Issue by goiihacker** [zerotier/libzt#53]
I am building the libzt project in windows os(I have the full code eg lwip). I start a command from vs2017 ,then cd to libzt directroy, execute the dist.sh but there are some error .

1 CMake Error at CMakeLists.txt:518 (install):
  install Library TARGETS given no DESTINATION!
I fix this error by deleting the related following rule at  CMakeLists.txt:518 

//the following rule looks like for dll
install (TARGETS ${DYNAMIC_LIB_NAME}
        LIBRARY DESTINATION lib
) 

2 then ,I rebuild libzt ,and get many errors ,and the error contains the following information

D:\share\libzt_f1\src\VirtualTap.cpp(82): error C2039: 'pipe': is not a member of 'global namespace'' [D:\share\libz
t_f1\WinBuild64\libzt_obj.vcxproj]
  D:\share\libzt_f1\src\VirtualTap.cpp(82): error C3861: 'pipe': identifier not found [D:\share\libzt_f1\WinBuild64\lib
zt_obj.vcxproj]
  D:\share\libzt_f1\src\VirtualTap.cpp(93): error C2039: 'write': is not a member of 'global namespace'' [D:\share\lib
zt_f1\WinBuild64\libzt_obj.vcxproj]
  D:\share\libzt_f1\src\VirtualTap.cpp(93): error C3861: 'write': identifier not found [D:\share\libzt_f1\WinBuild64\li
bzt_obj.vcxproj]
  D:\share\libzt_f1\src\VirtualTap.cpp(98): error C2039: 'close': is not a member of 'global namespace'' [D:\share\lib
zt_f1\WinBuild64\libzt_obj.vcxproj]
  D:\share\libzt_f1\src\VirtualTap.cpp(98): error C3861: 'close': identifier not found [D:\share\libzt_f1\WinBuild64\li
bzt_obj.vcxproj]
  D:\share\libzt_f1\src\VirtualTap.cpp(99): error C2039: 'close': is not a member of 'global namespace'' [D:\share\lib
zt_f1\WinBuild64\libzt_obj.vcxproj]
  D:\share\libzt_f1\src\VirtualTap.cpp(99): error C3861: 'close': identifier not found [D:\share\libzt_f1\WinBuild64\li
bzt_obj.vcxproj]

as your know ,the pipe and write api are the linux apis. and the pipe is a simplex ,Ok .now how can I build the libzt for windows ?If can I get the .lib library without modifying any code  or modiying less code?

Thank you!

**Comment by Setitch** [comment]
Down worry, under llinux you cannot compile it too...

**Comment by joseph-henry** [comment]
Thanks for bringing this to my attention. I believe these issues are fixed in the most recent version.

Run `./dist.bat` and everything should compile now. I've also updated the download link: https://download.zerotier.com/dist/sdk to include Windows DLLs. 

In this latest version there are a couple of changes to be aware of:
 - Main C API header has been renamed to `ZeroTierSockets.h`
 - Error reporting scheme and values have changed slightly (see header file)
 - Event code values have changed significantly (see header file)

Let me know if this issue persists or you discover anything else.
