### ISSUE TITLE
how to run http server and http client powered by libzt 

### ISSUE THREAD

**Issue by cloudfirst** [zerotier/libzt#79]
after reading the document, I understand the principle how libzt works. 
now the question is how to run a http server and http client powered by libzt.

the first idea is to re-compile the source code of http server and client by replacing all OS-socket API with zt-socket API.  however it seems that the code change workload maybe overhead. 

the second idea is to setup forward http proxy before http client, and reverse http proxy before http server, like below 

http client <-> forward http proxy -------------- reverse http proxy <-> http server

based on this arch,  only http proxy need code change to replace OS-socket API with zt-socket API. 

any suggestion ?

**Comment by joseph-henry** [comment]
That should work. You should also consider the performance impact of adding a third component (the proxy). You may see slightly better performance from just recompiling and replacing the client/server code as you mentioned, but it all depends on your application.

I think since the client/server likely uses API edge cases which may not be handled exactly the same in libzt it would be easiest to use your libzt-powered-proxy idea.

Another option may be to build a shim/intercept that maps the socket calls to their zts_ counterparts and then use something like LD_PRELOAD or DYLD_* to intercept the calls from an unmodified http client/server. I've done this in the past and it does work in most cases.

**Comment by cloudfirst** [comment]
thanks joseph-henry for your feedback. 

two more question : 
Q1: is there similare method like LD_PRELOAD or DYLD_* in windows ?  I can only find DLL injection by Google.  have you ever try it in windows ? 

Q2: data transfer between two processes powered by libzt in two machie, vs data transfer between two process powered by zerotier driver,  which is better on performance & throughput ?   assuming everything is the same except one powered by libzt, another powered by zerotier driver.   
Q2 can also be describe as :  is lwip same performance as OS tcp/ip stack ? if not, how much loss in performance ?

**Comment by joseph-henry** [comment]
No problem. To answer your questions:

1. I think `DLL Injection` is the term you're looking for on Windows. I don't have experience with it on Windows but if you run into problems I can try to help. The problem with intercepting is that the technique often changes over time for different platforms rendering the intercept useless (I think macOS made it impossible without disabling SIP, Android tries to prevent it, etc).

2. I would think transfers using the normal ZeroTier driver would be slightly faster than going through lwip. But I do not know the performance difference off hand.
