### ISSUE TITLE
[android] how can i get assignedAddresses

### ISSUE THREAD

**Issue by minjunlan** [zerotier/libzt#83]
how can i get assignedAddresses in android?
ZeroTierEventListener is  only return  resultCode, I want get assignedAddresses, how can i do in android?

**Comment by joseph-henry** [comment]
Java sources have been brought up to date and significantly enhanced since this ticket was opened.

An example of how to get IP addresses can be found in [test/selftest.java](https://github.com/zerotier/libzt/blob/master/test/selftest.java). See `getIPv4Address`

There's a new workflow file [.github/workflows/jar.yaml](https://github.com/zerotier/libzt/blob/master/.github/workflows/jar.yaml) that builds this on `ubuntu-latest`. I plan to add support for other platforms soon. Also, there's new Java API documentation coming this week. Hopefully that will be of some use.

**Comment by joseph-henry** [comment]
Closing in favor of discussion here: https://github.com/zerotier/libzt/issues/119
