### ISSUE TITLE
Joseph or people make for me i Pay for you

### ISSUE THREAD

**Issue by eduardojijoca** [zerotier/libzt#90]
Joseph or people make for me i Pay for you

**Comment by joseph-henry** [comment]
Please describe here what you need.

**Comment by eduardojijoca** [comment]
I NEED implement Zerotier Lib in my SOurce Laucher Game in C++ (Visual Studio 2019)

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by eduardojijoca** [comment]
Tell me whatsapp for talk with you. I NEED to implement Zerotier in my Source Game.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by joseph-henry** [comment]
For this sort of thing you should either:

1) Explain what you've tried so far and tell me what isn't working for you so that I can help you *here*.
2) Create a ticket via our [contact form](https://www.zerotier.com/contact/) so that we can communicate privately via our ticket system.

This library is written in C and can be included in a C++ project with literally no modification. Have you taken a look at the [examples](https://github.com/zerotier/libzt/tree/master/examples/cpp)?

**Comment by joseph-henry** [comment]
Also Eduardo, I'm not sure if you know this but anything you send in response to this thread is publicly viewable on the libzt github page. That is why I removed your phone number. You should not include private information unless you use our contact form.
